### ISSUE TITLE
Game DC's whenever effect monsters needs 3 or more tributes

### ISSUE THREAD

**Issue by GaudiFanYAY** [duelists-unite/srvpro#2]
**Describe the disconnect**
This disconnect seems to only happen with +3 tribute summons and Infernoid Tierra. Tributing for effects and fusion summoning other monsters (regardless of whether the fusion materials are set (like with Cyber End Dragon) or whatever the player chooses (like Chimeratech Overdragon), regardless of whether the player uses a Polymerization-like spell (hand or field), Future Fusion-like (deck) spell or contact-fusion) seem to be working fine.

**Details**
* Time: I do not understand this field, but it is not relevant to replicating the issue
* YGOPro2 Username: Sax
* AI Name: was chalanging my friend
* Platform: PC

**To Reproduce**
Steps to reproduce the disconnect:
1. Just trying to summon any monster to the field that needs 3 or more tributes

**Screenshots**
No screenshots available

**Replays**
Multiple where made:
https://cdn.discordapp.com/attachments/326470091032231936/605506970325221379/TierraDC.yrp3d
https://cdn.discordapp.com/attachments/326470091032231936/605506974192238603/TowerDC.yrp3d
https://cdn.discordapp.com/attachments/326470091032231936/605506978109718562/SkybaseTestDC.yrp3d

The following is a mix of DC not happening and happening when testing for this. They are from my friend: Gaudi
https://cdn.discordapp.com/attachments/326470091032231936/605839474970066958/07-30205032.yrp3d
https://cdn.discordapp.com/attachments/326470091032231936/605839477532786691/07-30205436.yrp3d
https://cdn.discordapp.com/attachments/326470091032231936/605839480490033153/07-30205034.yrp3d

**Comment by wSedlacek** [comment]
I have not been able to replicate this issue in 3-4 test with the AI. You mentioned this was against your friend? Does this issue occur only against him or against the AI or against other players as well?

**Comment by GaudiFanYAY** [comment]
Hey there, sorry for the slow reply.

The disconnect also occours against the AI too. There has been no attempt against other players yet, because it's only him and me that like to play in our friend group. But if you are able to, we can set up a time and try there? We use UTC +01:00 time here.

Also, would it help to knwo that we are using the released when the new server was added?
It was available though this link: https://mega.nz/#!ztMQkKpY!zFJD2k20I-PH2qB4pj9b_6UBE-HkzeHItC8LcBOEVyU

**Comment by wSedlacek** [comment]
Thanks very much for the report. New clients will new updated here - https://github.com/duelists-unite/YGOPro2/releases

A beta version of the server soon will be available (probably over this weekend) using the https://github.com/duelists-unite codebase. Keep me posted if you continue to have this issue or gather any additional information.

**Comment by wSedlacek** [comment]
I have migrated over to a ubuntu based server and have fixed two other issues by this. 
Let us know if you still have issues.
