### ISSUE TITLE
Disconnect every time BLS link is summoned

### ISSUE THREAD

**Issue by hafizhmakmur** [duelists-unite/srvpro#4]
**Describe the disconnect**
Everytime I try to summon <Black Luster Soldier, Soldier of Chaos>, the server disconnects.

**Details**
* Time: Anytime
* YGOPro2 Username: YGOPro2
* AI Name: any AI
* Platform: Windows

**To Reproduce**
Steps to reproduce the disconnect:
1. Summon <Black Luster Soldier, Soldier of Chaos> by any means

**Screenshots**
-

**Replays**
-

**Comment by wSedlacek** [comment]
Seems like we have a missing script for that monster. I am working on a new updater and this should be fixed soon. Thanks for the report!

**Comment by wSedlacek** [comment]
I have moved over to ubuntu for the server and this appears to now be resolved.
![2019-08-04 21 27 06](https://user-images.githubusercontent.com/8206108/62436378-0ea62600-b705-11e9-9eb6-3c0021eddb15.gif)
