### ISSUE TITLE
Get disconnected trying to summon Beat Cop

### ISSUE THREAD

**Issue by Sextonmal** [duelists-unite/srvpro#5]
Every time I try to summon Beat Cop from the Underworld I get disconnected.
 Time: 10:40am 8/4/2019
* YGOPro2 Username: sextonmal
* AI Name: 
* Platform: Windows

**To Reproduce**
Steps to reproduce the disconnect:
1. Go to any duel (AI or online vs)
2. Try to summon Beat Cop from the Underworld
3. The system will disconnect at that time

**Comment by wSedlacek** [comment]
This issue should now be resolved. I believe this was the same issue as https://github.com/duelists-unite/srvpro/issues/4

![2019-08-04 22 15 31](https://user-images.githubusercontent.com/8206108/62436501-778d9e00-b705-11e9-9305-172f1cfcfaf5.gif)
